/* 5:16:39 PM Local */ SHOW VARIABLES;
/* 5:16:39 PM Local */ SELECT @@global.max_allowed_packet;
/* 5:16:39 PM Local */ SHOW DATABASES;
/* 5:16:47 PM Local */ USE `amp_backend`;
/* 5:16:47 PM Local amp_backend */ SHOW VARIABLES LIKE 'character_set_database';
/* 5:16:47 PM Local amp_backend */ SHOW /*!50002 FULL*/ TABLES;
/* 5:16:47 PM Local amp_backend */ SELECT * FROM information_schema.routines WHERE routine_schema = 'amp_backend' ORDER BY routine_name;
/* 5:17:29 PM Local amp_backend */ SHOW TABLES IN information_schema LIKE 'ENGINES';
/* 5:17:29 PM Local amp_backend */ SELECT Engine, Support FROM `information_schema`.`engines` WHERE SUPPORT IN ('DEFAULT', 'YES') AND Engine != 'PERFORMANCE_SCHEMA';
/* 5:17:29 PM Local amp_backend */ SHOW VARIABLES LIKE 'default_storage_engine';
/* 5:17:29 PM Local amp_backend */ SHOW VARIABLES LIKE 'collation_database';
/* 5:17:29 PM Local amp_backend */ SELECT * FROM `information_schema`.`character_sets` ORDER BY `character_set_name` ASC;
/* 5:17:29 PM Local amp_backend */ SELECT * FROM `information_schema`.`collations` WHERE character_set_name = 'utf8mb4' ORDER BY `collation_name` ASC;
/* 5:17:37 PM Local amp_backend */ CREATE TABLE `test` (id INT(11) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT);
/* 5:17:37 PM Local amp_backend */ SHOW TABLE STATUS LIKE 'test';
/* 5:17:37 PM Local amp_backend */ SHOW CREATE TABLE `test`;
/* 5:17:37 PM Local amp_backend */ SET NAMES 'utf8mb4';
/* 5:17:37 PM Local amp_backend */ SELECT * FROM `test` LIMIT 0,1000;
/* 5:17:37 PM Local amp_backend */ SHOW INDEX FROM `test`;
